---
homelab:
  children:

    routers:
      hosts:
        10.0.0.1:
          ansible_network_os: ios
          ansible_connection: network_cli


    switches:
      hosts:
        172.16.99.1:
          ansible_network_os: junos
          ansible_connection: netconf

  vars:
    ansible_user: admin
    ansible_password: XXXXXXXX


